[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prank_machine"
version = "0.1.0"
authors = [
    { name = "fin-vermehr" }
]
description = "A prank device that plays sounds in the dark"
requires-python = ">=3.11"
dependencies = [
    "pytest",
    "pygame",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]